hal: apollo3: fix few 1 << 31 constants
Fix few 1 << 31 constants that have been generated as -2147483648 and
cause some c++ warnings:

/__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include/apollo3.h:16343:3:
error: this decimal constant is unsigned only in ISO C90 [-Werror]

These are really just 1 << 31 and should be declared as literal
unsigned, ideally they'll all be fixed but let's just adjust these for
now, I presume the file is generated, no point generating a huge delta.

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>